/**
 * This file is automatically generated by Gulp.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 * @author Riley Ren
 * Date: 2015-04-03 18:32:11
 * 
 */

(function() {
    console.log("hello coffee");

}).call(this);