var gulp = require('gulp');
var header = require('gulp-header');
var gutil = require('gulp-util');
var colors = gutil.colors;
var coffee = require('gulp-coffee');
var uglify = require('gulp-uglify');
var beautify = require('gulp-js-beaut');
var minifyCSS = require('gulp-minify-css');
var sass = require('gulp-sass');
var cached = require('gulp-cached');
var util = require('util');
var path = require('path');
var moment = require('moment');
var del = require('del');
var gulpif = require('gulp-if');
var jade = require('gulp-jade');

var options = {
    "tasks": {
        "jade": {
            "src": 'jade/**/*.jade',
            "dist": './',
            "cache": 'jade'
        },
        "coffee": {
            "src": 'coffee/**/*.coffee',
            "dist": 'js/',
            "cache": 'coffee'
        },
        "sass": {
            "src": 'sass/**/*.sass',
            "dist": 'css/',
            "cache": 'sass'
        },
        "copy:js": {
            "src": 'coffee/**/*.js',
            "dist": 'js/',
            "cache": 'copy:js'
        },
        "copy:css": {
            "src": 'sass/**/*.css',
            "dist": 'css/',
            "cache": 'copy:css'
        },
        "copy:html": {
            "src": 'jade/**/*.html',
            "dist": './',
            "cache": 'copy:html'
        }
    },
    "env": "development"
};

function now() {
    return moment().format("YYYY-MM-DD HH:mm:ss");
}

function log(){
    var text = util.format.apply(null, arguments);
    gutil.log(text);
}

var banner = '';
banner += '/**\n';
banner += ' * This file is automatically generated by Gulp.\n';
banner += ' * Do not modify this file -- YOUR CHANGES WILL BE ERASED!\n';
banner += ' * @author Riley Ren\n';
banner += ' * Date: ' + now() + '\n';
banner += ' * \n';
banner += ' */\n';
banner += '\n';


gulp.task('jade', function() {
    var o = options.tasks.jade;
    return gulp.src(o.src)
        .pipe(cached(o.cache))
        .pipe(jade({}))
        .pipe(gulpif(options.env !== 'production', beautify({})))
        .pipe(gulp.dest(o.dist));
});


gulp.task('coffee', function() {
    var o = options.tasks.coffee;
    return gulp.src(o.src)
        .pipe(cached(o.cache))
        .pipe(coffee({}).on('error', gutil.log))
        .pipe(header(banner))
        .pipe(beautify({}))
        .pipe(gulpif(options.env === 'production', uglify()))
        .pipe(gulp.dest(o.dist));
});

gulp.task('sass', function() {
    var o = options.tasks.sass;
    return gulp.src(o.src)
        .pipe(cached(o.cache))
        .pipe(sass({indentedSyntax: true}))
        .on('error', gutil.log)
        .pipe(header(banner))
        .pipe(beautify({quiet: true}))
        .pipe(gulpif(options.env === 'production', minifyCSS()))
        .pipe(gulp.dest(o.dist));
});

gulp.task('copy:js', function() {
    var o = options.tasks['copy:js'];
    return gulp.src(o.src)
        .pipe(cached(o.cache))
        .pipe(gulpif(options.env === 'production', uglify()))
        .pipe(gulp.dest(o.dist));
});


gulp.task('copy:css', function() {
    var o = options.tasks['copy:css'];
    return gulp.src(o.src)
        .pipe(cached(o.cache))
        .pipe(gulpif(options.env === 'production', minifyCSS()))
        .pipe(gulp.dest(o.dist));
});


gulp.task('copy:html', function() {
    var o = options.tasks['copy:html'];
    return gulp.src(o.src)
        .pipe(cached(o.cache))
        // .pipe(gulpif(options.env === 'production', minifyCSS()))
        .pipe(gulp.dest(o.dist));
});


gulp.task('clean', function(cb) {
    del(['js/**/*.js', 'css/**/*.css', './**/*.html', '!./jade/**/*.html'], cb);
});

function watchFatory(srcPath, taskName, cacheName) {
    var watcher = gulp.watch(srcPath, [taskName]);
    watcher.on('change', function (event) {
        var relativePath = path.relative(path.resolve('.'), event.path);
        log("File %s was %s, running tasks...", colors.magenta(relativePath), colors.cyan(event.type));
        if (event.type === 'deleted') {
            try{
                delete cached.caches[cacheName][event.path];

            } catch(e) {}
        }
    });
}

gulp.task('watch', function () {
    for(var prop in options.tasks) {
        if(options.tasks.hasOwnProperty(prop) && options.tasks[prop]) {
            var o = options.tasks[prop];
            watchFatory(o.src, prop, o.cache);
        }
    }
});

gulp.task('development', function () {
    options.env = "development";
});

gulp.task('production', function () {
    options.env = "production";
});

var tasks = [];

(function(){
    for(var prop in options.tasks) {
        if(options.tasks.hasOwnProperty(prop) && options.tasks[prop]) {
            tasks.push(prop);
        }
    }
})();

gulp.task('default', ['watch'].concat(tasks));

gulp.task('compile', ['development'].concat(tasks));

gulp.task('build', ['production'].concat(tasks));